name: GodelScript Build

on:
  push:
    branches: [ main, lhk_dev ]
  pull_request:
    branches: [ main, lhk_dev ]

jobs:
  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd godel-script
        cd godel-backend/souffle
        git am ../0001-init-self-used-souffle-from-public-souffle.patch
        cd ../..
        mkdir build
        cd build
        cmake ..
        make -j4